# .github/workflows/test.yml
name: Test Rich Results Action

on:
  push: # Run on every push to any branch
  pull_request: # Run on pull requests targeting any branch
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  test:
    runs-on: ubuntu-latest # Use the same OS as most users likely will

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Match the node version specified in action.yml
          cache: "npm" # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Use 'ci' for cleaner installs in CI

      - name: Run the action locally
        id: test-action # Give the step an ID to access outputs
        # Use './' to reference the action in the current repository
        uses: ./
        with:
          # Use a simple, publicly accessible URL for testing
          url: "https://signoz.io"
          # Use the default output directory for this test
          # output-directory: 'test-output' # Or specify a different one

      - name: Print Outputs
        if: always() # Run this even if the action step fails, to see partial outputs
        run: |
          echo "--- Action Outputs ---"
          echo "Check Result: ${{ steps.test-action.outputs.check-result }}"
          echo "Screenshot Path: ${{ steps.test-action.outputs.screenshot-path }}"
          echo "Logs Path: ${{ steps.test-action.outputs.logs-path }}"
          echo "HTML Path: ${{ steps.test-action.outputs.html-path }}"
          echo "----------------------"

      - name: Upload Test Artifacts
        if: always() # Always upload artifacts, even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: test-run-artifacts
          # Upload the entire default output directory
          path: rich-results-output/
          # Or be more specific if needed:
          # path: |
          #   ${{ steps.test-action.outputs.screenshot-path }}
          #   ${{ steps.test-action.outputs.logs-path }}
          #   ${{ steps.test-action.outputs.html-path }}
